### ISSUE TITLE
help with Drive.py

### ISSUE THREAD

**Issue by Akshaysanthosh** [yazeedalrubyli/SDRC#5]
One i run drive.py and command to collect image, it starts to take images but when i try to control using keys - W,A,S,D on my keyboard nothing happens , please help me with this

**Comment by yazeedalrubyli** [comment]
Checked and works fine. Try to change the keys within the code and see if anything happens.

If the issue persists, please let me know.

**Comment by Akshaysanthosh** [comment]
hey this my exact issue , while i run this Drive.py script ( drive.py -c ) for collecting images + steering data , The pie cam is taking photos but nothing is taking place at terminal so that i can enter W,A,S,D key and it get recorded ..i haven't built the circuit using L293D is that issue for not recording steering data ??  . Iam checking put whether the script works not .

If you can post a vedio record of what happing on your computer scrren (pi ) , It would be really helpfull 

I am attaching  the screenshots [https://drive.google.com/drive/folders/1NtHubNznHiwa_YWuVSGE7Zch6Yx3R5IQ?usp=sharing(url)
